### ISSUE TITLE
Animation of button 

### ISSUE THREAD

**Issue by AnshumanFauzdar** [tuhinpal/Contact-Form#6]
Forms work great but due to non-activity of button it might not be eye catching for end user and adding animation to the button will provide more attraction and ultimately provide call-to-action for end-user to contact through form.

Animation can be implemented in elegant way without disturbing end-users.

**Comment by cachecleanerjeet** [comment]
Hopefully soon!

**Comment by AnshumanFauzdar** [comment]
Hey @cachecleanerjeet I am trying to implement animation check here - me.anshumanfauzdar.me

Maybe I will try to finalize in October [HACKTOBERFEST :)]

**Comment by AnshumanFauzdar** [comment]
Hey @cachecleanerjeet I have opened a PR #7 with added animation and other changes.
Demo:

https://user-images.githubusercontent.com/40523329/135589373-936774b1-5227-4cf9-9134-c740bab74dfc.mp4

**Comment by AnshumanFauzdar** [comment]
Hey @tuhinpal look at [this](https://github.com/idoco/intergram)

**Comment by tuhinpal** [comment]
Feel free to open it if not resolved!
