### ISSUE TITLE
Once a contact query is sent another query can be sent unless we clear cookies.

### ISSUE THREAD

**Issue by avasthi-git** [tuhinpal/Contact-Form#8]
I understand this may be to prevent spam, but in personal websites they is no spam as such. So please tell a solution to get the form after submitting one :)

**Comment by avasthi-git** [comment]
I understand this may be to prevent spam, but in personal websites they is no spam as such. So please tell a solution to get the form after submitting one :)

**Comment by tuhinpal** [comment]
Simple, here we go:

```
<script
  src="https://cdn.jsdelivr.net/gh/tuhinpal/contact-form@master/src/contact-form.min.js"
  id="contactform"
  error_text=""
  success_text=""
  disable_waittime="false"
  form_worker_url="https://contact-form.tprojects.workers.dev/"
></script>
```

Make `disable_waittime` to `"false"`

**Comment by tuhinpal** [comment]
Feel free to open it if it is not resolved!
